title: Nebula Digital Tech
author: Kincc
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Digital Data manager based on Bloackchian and NLP

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username: Kincc-9999

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
